### ISSUE TITLE
Please add keyboard shortcut to copy result. Copy full line behaviour for the expressions is another wish.

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#22]
It would be fantastic if I could **copy the result** of an expression to the clipboard via a keyboard shortcut. _Listary_ has this as an example:
![Listary-copy_result](https://user-images.githubusercontent.com/32457827/84560632-2ba87e00-ad46-11ea-88e3-ad6ac5fe25b2.png)

While talking about copying to the clipboard:
I really like _Visual Studio Code_'s behaviour to **copy the full line** when having no character selected. This would be cool for the expression side of _Parsify_ as well I think. 😉

Thanks

**Comment by LarsJandel** [comment]
...and _Visual Studio Code_'s `Ctrl+X` behaviour to cut the full line when no characters are selected. 😎
Thanks!

**Comment by xxczaki** [comment]
Great idea, I will try to work on it.

**Comment by xxczaki** [comment]
The 1.4.0 (which should be available within a few hours) will include the ability to `copy the result` and` paste it into the last line` using buttons next to the result. I'm hoping to make this feature configurable in the next release, so that you will be able to customize the behavior (for example copy the full line) :smile:

Preview: https://twitter.com/parsifyapp/status/1325936657246326784

**Comment by LarsJandel** [comment]
Thanks for adding this!
In addition to the buttons, I still would like an option to quickly copy the result via a keyboard shortcut, avoiding the need to use the mouse. 😉
Thanks!

**Comment by xxczaki** [comment]
@LarsJandel The system was changed a bit in the recent `1.5.0` release (added option to copy the full line via a double-click), but it still does not support keyboard shortcuts. What shortcut would you like to use in order to copy results?

I was thinking about `Ctrl/Cmd + <number>` for example `Cmd + 3` to copy the result from line 3. However, I don't think this would work for anything over line 9.

**Comment by LarsJandel** [comment]
Nice idea using the line numbers, but I think, it doesn't have to be that complicated, plus regarading the limit and using separator lines / comments, it wouldn't be handy that way as you mentioned yourself.
It should be sufficient, if the user could copy the result of the formula where the cursor is currently positioned. This should be the most common use case.
Hm, regarding the short cut. Thinking about it, _Listary_ didn't go for `Ctrl/Cmd+C` as this is still in use to copy highlighted text, so using `1` being close to the modifier key, works well. ...it also translates to _copy one_ (result) 😉. So, you could do just the same:
`Ctrl/Cmd+1` to copy the result of line of the current cursor location.

Thanks!

**Comment by xxczaki** [comment]
@LarsJandel Sorry for the delay, and thanks for further details. For your information, the discussed feature (keyboard shortcuts for copying lines, copy full line) will be available in the next release, which should be released at the end of February :smile:

**Comment by xxczaki** [comment]
Implemented!

- `Ctrl/Cmd + C` copies full line if no selection
- `Ctrl/Cmd + X` removed line if no selection
- `Ctrl/Cmd + 1` copies the result of a line

^ This will be added to the "Shortcuts help" modal (bottom-left corner of the app).

**Comment by LarsJandel** [comment]
Fantastic - thanks! 🎉
