### ISSUE TITLE
Unhandled promise rejection on startup

### ISSUE THREAD

**Issue by ecciv** [parsify-dev/desktop#32]
Not sure what's up but each time I open Parsify, I get an error like this, and the input side of the app is replaced by a white box saying "An unexpected error occurred.". Can't get it to run! On 1.4.1 now, this error is new to me.

Unhandled Promise Rejection
TypeError: Cannot read property 'value' of undefined
    at IpcMainImpl.<anonymous> (C:/Users/Victor/AppData/Local/Programs/parsify-desktop/resources/app.asar/app/background.js:1:11092)

**Comment by xxczaki** [comment]
If you care about your configuration, you can modify the `preferences.json` file inside the `Parsify Desktop` folder, which is located in %appdata%. Open it with any editor and add a missing property (do not include the `+` symbols):

```diff
{
	"preferences": [
		...
	      {
		  "name": "configuration",
		  "value": ""
+	      },
+             {
+	          "name": "fontSize",
+	          "value": "1rem"
+             }
	],
	...
}
```

**If you don't manage to do it, just sent me this file to my email (a@kepinski.me) and I will do it for you.**

In case you don't really care about your configuration, go ahead and just delete the whole `Parsify Desktop` folder inside %appdata% - the configuration will reset and everything will work fine.

---

I'm sorry about this inconvenience, but this is an issue with the problematic user configuration storage used in Parsify Desktop. I'm thinking about using a different solution for that in the upcoming release, so that such problems won't occur in the future :)

**Comment by ecciv** [comment]
Thanks! I got it to work. 

Also I was trying out to see if Parsify will solve equations and the input side crashes when I write solve(-any equation here-). What's up with that?

**Comment by xxczaki** [comment]
@ecciv Glad to hear that it works 😄 Parsify currently does not support equation solving (for example `x + 2 = 3`). I would really like to support it, but currently, it would be incredibly hard to implement. But because the math parser in Parsify is based on [Math.js](https://mathjs.org/), they might implement it at some point, as it seems like a requested feature (see https://github.com/josdejong/mathjs/issues/38 and mentioned issues/PRs).

**Comment by joaovicentefs** [comment]
Hi mate @xxczaki i'm prouded  user of Parsify. 
After update from 1.2.2 to the 1.4.1 version i allways receive a similar message when startup the app. This is the message:

> Unhandled Promise Rejection
> TypeError: Cannot read property 'value' of undefined
>     at IpcMainImpl.<anonymous> (/opt/Parsify Desktop/resources/app.asar/app/background.js:1:11092)

Do you know how can i hanndle with this? As an workaround i'm did an downgrade to 1.2.2 version
To give you more information my OS is Ubuntu 20.10

**Comment by xxczaki** [comment]
The configuration storage was completely refactored in version `1.5.0` and this issue will no longer occur. Please update :smile:

https://download.parsify.app
