### ISSUE TITLE
Dynamic window resizing doesn't work as expected

### ISSUE THREAD

**Issue by johnnaaron** [parsify-dev/desktop#68]
Application window has a very large default minimum width/height, and does not allow for smaller resizing. This is bad for accessibility, low-dpi monitors, and small screen resolutions. 

The attached screenshot shows the wasted window space during general use. 
The screen recording illustrates the resizing issue.

![wasted-space](https://user-images.githubusercontent.com/32317888/173182062-d47eeb10-ce9a-456d-89f0-edd8f95b01d9.png)

https://user-images.githubusercontent.com/32317888/173182057-9e59f309-970c-4345-9ec9-76549813b77d.mp4

I think your project is the closest alternative to Numi for win/linux, so I'm really excited to see where it goes in the future!

**Comment by tnaseem** [comment]
Agreed. It'd be good to remove this limit on window sizing as I'm facing the same issue.

As a side note, I was about to buy the full version but noticed there have been no updates since April. So will hold off for now until I know it's still being actively developed. I'm sure it is - just being cautious!

**Comment by xxczaki** [comment]
@johnaaron-git @tnaseem Thank you so much for your patience; please see https://headwayapp.co/parsify-changelog/2-0-0-230230.
